# Generated by Django 4.1.6 on 2023-02-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo1', models.CharField(max_length=200)),
                ('tipo2', models.CharField(max_length=200)),
                ('altura', models.CharField(max_length=200)),
                ('peso', models.CharField(max_length=200)),
                ('inv', models.CharField(max_length=200)),
            ],
        ),
    ]
